-- DROP TABLE IF EXISTS ACCOUNTS;

-- CREATE TABLE ACCOUNTS (
--   account_number INT AUTO_INCREMENT  PRIMARY KEY,
--   name VARCHAR(250) NOT NULL,
--   address VARCHAR(250) NOT NULL,
--   dob DATE NOT NULL
-- );